### ISSUE TITLE
Text export addition issue

### ISSUE THREAD

**Issue by smramgator** [markusfisch/Libra#15]
Love the app, but there seems to be a bug where the text version of sharing an issue gives the correct scores but is one less than what it should be (as in, one closer to zero). Here's a sample output:

Cons
*  -5 Have to move to new city
*  -4 Moving away from friends
*  -3 Cost of moving
= -11

Pros
*   1 Bigger city than before
*   3 More job growth options
*   5 Less strict expectations 
*   7 Less restrictive job duties
=  15

Note that it should be -12 and 16 instead of -11 and 15

**Comment by markusfisch** [comment]
Ah, this is a bug 🙈 Thanks for filing an issue! 👍 

The total was calculated before the categorization so the Pro argument "1 Bigger city than before" was added to Cons.

Fixed in https://github.com/markusfisch/Libra/commit/fa309f90e21052774db6d173e2bb0d217f386347

A new version (1.12.4) is on it's way through Google Play and should become available within the next few hours. You may also get it directly from GitHub here:
https://github.com/markusfisch/Libra/releases/tag/1.12.4

**Comment by smramgator** [comment]
Wow, thank you so much! Super awesome of you to fix that so quickly.  I got the app on F-droid, idk if you need to do anything special for that portal.  I'll use the gplay version just to make it easier to update 
-------- Original message --------From: Markus Fisch ***@***.***> Date: 2/3/23  9:42 AM  (GMT-05:00) To: markusfisch/Libra ***@***.***> Cc: smramgator ***@***.***>, Author ***@***.***> Subject: Re: [markusfisch/Libra] Text export addition issue (Issue #15) 

Ah, this is a bug 🙈 Thanks for filing an issue! 👍

The total was calculated before the categorization so the Pro argument "1 Bigger city than before" was added to Cons.

Fixed in fa309f9

A new version (1.12.4) is on it's way through Google Play and should become available within the next few hours. You may also get it directly from GitHub here:

https://github.com/markusfisch/Libra/releases/tag/1.12.4
